# Generated by Django 5.0.4 on 2024-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_body_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.TextField(verbose_name='deixe sua mensagem')),
            ],
            options={
                'verbose_name': 'Contato',
                'ordering': ['-data'],
            },
        ),
    ]
