# Generated by Django 5.0.4 on 2024-04-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
        ('blog', '0005_contato_telefone'),
    ]

    operations = [
    ]
